spring:
  datasource:
    driver-class-name:
      com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/performance?serverTimezone=Asia/Seoul
    username: root
    password: root0000

  jpa:
    show-sql:
      true
    generate-ddl:
      true
    hibernate:
      ddl-auto:
         update
    properties:
      hibernate:
        format_sql: true
        
jwt:
  secret:
    key: "jwtsecretkeyjwtsecretkeyjwtsecretkeyjwtsecretkeyjwtsecretkey"